// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from wire.proto

package de.pokerno.protocol.wire;

public enum DealType implements com.dyuproject.protostuff.EnumLite<DealType>
{
    BOARD(1),
    HOLE(2),
    DOOR(3);
    
    public final int number;
    
    private DealType (int number)
    {
        this.number = number;
    }
    
    public int getNumber()
    {
        return number;
    }
    
    public static DealType valueOf(int number)
    {
        switch(number) 
        {
            case 1: return BOARD;
            case 2: return HOLE;
            case 3: return DOOR;
            default: return null;
        }
    }
}
