// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from cmd.proto

package proto.cmd;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class KickPlayerSchema
       implements Schema<de.pokerno.protocol.cmd.KickPlayer> {


    static final de.pokerno.protocol.cmd.KickPlayer DEFAULT_INSTANCE = new de.pokerno.protocol.cmd.KickPlayer();
    static final Schema<de.pokerno.protocol.cmd.KickPlayer> SCHEMA = new KickPlayerSchema();

    public static de.pokerno.protocol.cmd.KickPlayer getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<de.pokerno.protocol.cmd.KickPlayer> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_PLAYER = 1;
    public static final int FIELD_REASON = 2;

    public KickPlayerSchema() {}


    public de.pokerno.protocol.cmd.KickPlayer newMessage() {
        return new de.pokerno.protocol.cmd.KickPlayer();
    }

    public Class<de.pokerno.protocol.cmd.KickPlayer> typeClass() {
        return de.pokerno.protocol.cmd.KickPlayer.class;
    }

    public String messageName() {
        return de.pokerno.protocol.cmd.KickPlayer.class.getSimpleName();
    }

    public String messageFullName() {
        return de.pokerno.protocol.cmd.KickPlayer.class.getName();
    }


    public boolean isInitialized(de.pokerno.protocol.cmd.KickPlayer message) {
        return true;
    }


    public void mergeFrom(Input input, de.pokerno.protocol.cmd.KickPlayer message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, de.pokerno.protocol.cmd.KickPlayer message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_PLAYER:
                message.setPlayer(input.readString());
                break;
            case FIELD_REASON:
                message.setReason(input.readString());
                break;
            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_PLAYER, FIELD_REASON };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, de.pokerno.protocol.cmd.KickPlayer message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, de.pokerno.protocol.cmd.KickPlayer message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_PLAYER:
                output.writeString(FIELD_PLAYER, message.getPlayer(), false);
                break;
            case FIELD_REASON:
                if (message.getReason() != null)
                    output.writeString(FIELD_REASON, message.getReason(), false);
                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_PLAYER: return "player";
            case FIELD_REASON: return "reason";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("player", FIELD_PLAYER);
        fieldMap.put("reason", FIELD_REASON);
    }
}
