// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from cmd.proto

package proto.cmd;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class PlayerEventSchema
       implements Schema<de.pokerno.protocol.cmd.PlayerEvent> {

    public enum EventType implements com.dyuproject.protostuff.EnumLite<EventType>
    {
        LEAVE(1),
        SIT_OUT(2),
        COME_BACK(3),
        OFFLINE(4),
        ONLINE(5);
        
        public final int number;
        
        private EventType (int number)
        {
            this.number = number;
        }
        
        public int getNumber()
        {
            return number;
        }
        
        public static EventType valueOf(int number)
        {
            switch(number) 
            {
                case 1: return LEAVE;
                case 2: return SIT_OUT;
                case 3: return COME_BACK;
                case 4: return OFFLINE;
                case 5: return ONLINE;
                default: return null;
            }
        }
    }


    static final de.pokerno.protocol.cmd.PlayerEvent DEFAULT_INSTANCE = new de.pokerno.protocol.cmd.PlayerEvent();
    static final Schema<de.pokerno.protocol.cmd.PlayerEvent> SCHEMA = new PlayerEventSchema();

    public static de.pokerno.protocol.cmd.PlayerEvent getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<de.pokerno.protocol.cmd.PlayerEvent> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_PLAYER = 1;
    public static final int FIELD_TYPE = 2;

    public PlayerEventSchema() {}


    public de.pokerno.protocol.cmd.PlayerEvent newMessage() {
        return new de.pokerno.protocol.cmd.PlayerEvent();
    }

    public Class<de.pokerno.protocol.cmd.PlayerEvent> typeClass() {
        return de.pokerno.protocol.cmd.PlayerEvent.class;
    }

    public String messageName() {
        return de.pokerno.protocol.cmd.PlayerEvent.class.getSimpleName();
    }

    public String messageFullName() {
        return de.pokerno.protocol.cmd.PlayerEvent.class.getName();
    }


    public boolean isInitialized(de.pokerno.protocol.cmd.PlayerEvent message) {
        return true;
    }


    public void mergeFrom(Input input, de.pokerno.protocol.cmd.PlayerEvent message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, de.pokerno.protocol.cmd.PlayerEvent message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_PLAYER:
                message.setPlayer(input.readString());
                break;
            case FIELD_TYPE:
                message.setType(EventType.valueOf(input.readEnum()));
                break;
            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_PLAYER, FIELD_TYPE };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, de.pokerno.protocol.cmd.PlayerEvent message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, de.pokerno.protocol.cmd.PlayerEvent message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_PLAYER:
                output.writeString(FIELD_PLAYER, message.getPlayer(), false);
                break;
            case FIELD_TYPE:
                output.writeEnum(FIELD_TYPE, message.getType().number, false);    break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_PLAYER: return "player";
            case FIELD_TYPE: return "type";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("player", FIELD_PLAYER);
        fieldMap.put("type", FIELD_TYPE);
    }
}
