// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from cmd.proto

package proto.cmd;

import java.io.IOException;

import com.dyuproject.protostuff.ByteString;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class ShowCardsSchema
       implements Schema<de.pokerno.protocol.cmd.ShowCards> {


    static final de.pokerno.protocol.cmd.ShowCards DEFAULT_INSTANCE = new de.pokerno.protocol.cmd.ShowCards();
    static final Schema<de.pokerno.protocol.cmd.ShowCards> SCHEMA = new ShowCardsSchema();

    public static de.pokerno.protocol.cmd.ShowCards getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<de.pokerno.protocol.cmd.ShowCards> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_PLAYER = 1;
    public static final int FIELD_CARDS = 2;
    public static final int FIELD_MUCK = 3;

    public ShowCardsSchema() {}


    public de.pokerno.protocol.cmd.ShowCards newMessage() {
        return new de.pokerno.protocol.cmd.ShowCards();
    }

    public Class<de.pokerno.protocol.cmd.ShowCards> typeClass() {
        return de.pokerno.protocol.cmd.ShowCards.class;
    }

    public String messageName() {
        return de.pokerno.protocol.cmd.ShowCards.class.getSimpleName();
    }

    public String messageFullName() {
        return de.pokerno.protocol.cmd.ShowCards.class.getName();
    }


    public boolean isInitialized(de.pokerno.protocol.cmd.ShowCards message) {
        return true;
    }


    public void mergeFrom(Input input, de.pokerno.protocol.cmd.ShowCards message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, de.pokerno.protocol.cmd.ShowCards message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_PLAYER:
                message.setPlayer(input.readString());
                break;
            case FIELD_CARDS:
                message.setCards(input.readBytes());
                break;
            case FIELD_MUCK:
                message.setMuck(input.readBool());
                break;
            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_PLAYER, FIELD_CARDS, FIELD_MUCK };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, de.pokerno.protocol.cmd.ShowCards message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, de.pokerno.protocol.cmd.ShowCards message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_PLAYER:
                output.writeString(FIELD_PLAYER, message.getPlayer(), false);
                break;
            case FIELD_CARDS:
                output.writeBytes(FIELD_CARDS, message.getCards(), false);
                break;
            case FIELD_MUCK:
                if (message.isMuck() != null)
                    output.writeBool(FIELD_MUCK, message.isMuck(), false);
                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_PLAYER: return "player";
            case FIELD_CARDS: return "cards";
            case FIELD_MUCK: return "muck";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("player", FIELD_PLAYER);
        fieldMap.put("cards", FIELD_CARDS);
        fieldMap.put("muck", FIELD_MUCK);
    }
}
