// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from msg.proto

package proto.msg;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class AddBetSchema
       implements Schema<de.pokerno.protocol.msg.AddBet> {


    static final de.pokerno.protocol.msg.AddBet DEFAULT_INSTANCE = new de.pokerno.protocol.msg.AddBet();
    static final Schema<de.pokerno.protocol.msg.AddBet> SCHEMA = new AddBetSchema();

    public static de.pokerno.protocol.msg.AddBet getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<de.pokerno.protocol.msg.AddBet> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_BET = 1;

    public AddBetSchema() {}


    public de.pokerno.protocol.msg.AddBet newMessage() {
        return new de.pokerno.protocol.msg.AddBet();
    }

    public Class<de.pokerno.protocol.msg.AddBet> typeClass() {
        return de.pokerno.protocol.msg.AddBet.class;
    }

    public String messageName() {
        return de.pokerno.protocol.msg.AddBet.class.getSimpleName();
    }

    public String messageFullName() {
        return de.pokerno.protocol.msg.AddBet.class.getName();
    }


    public boolean isInitialized(de.pokerno.protocol.msg.AddBet message) {
        return true;
    }


    public void mergeFrom(Input input, de.pokerno.protocol.msg.AddBet message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, de.pokerno.protocol.msg.AddBet message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_BET:
                message.setBet(input.mergeObject(message.getBet(), proto.wire.BetSchema.getSchema()));
                break;

            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_BET };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, de.pokerno.protocol.msg.AddBet message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, de.pokerno.protocol.msg.AddBet message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_BET:
                output.writeObject(FIELD_BET, message.getBet(), proto.wire.BetSchema.getSchema(), false);

                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_BET: return "bet";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("bet", FIELD_BET);
    }
}
