// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from msg.proto

package proto.msg;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class GameplayEventSchema
       implements Schema<de.pokerno.protocol.msg.GameplayEvent> {

    public enum EventType implements com.dyuproject.protostuff.EnumLite<EventType>
    {
        GAME(1),
        STAKE(2);
        
        public final int number;
        
        private EventType (int number)
        {
            this.number = number;
        }
        
        public int getNumber()
        {
            return number;
        }
        
        public static EventType valueOf(int number)
        {
            switch(number) 
            {
                case 1: return GAME;
                case 2: return STAKE;
                default: return null;
            }
        }
    }


    static final de.pokerno.protocol.msg.GameplayEvent DEFAULT_INSTANCE = new de.pokerno.protocol.msg.GameplayEvent();
    static final Schema<de.pokerno.protocol.msg.GameplayEvent> SCHEMA = new GameplayEventSchema();

    public static de.pokerno.protocol.msg.GameplayEvent getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<de.pokerno.protocol.msg.GameplayEvent> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_TYPE = 1;
    public static final int FIELD_GAME = 2;
    public static final int FIELD_STAKE = 3;

    public GameplayEventSchema() {}


    public de.pokerno.protocol.msg.GameplayEvent newMessage() {
        return new de.pokerno.protocol.msg.GameplayEvent();
    }

    public Class<de.pokerno.protocol.msg.GameplayEvent> typeClass() {
        return de.pokerno.protocol.msg.GameplayEvent.class;
    }

    public String messageName() {
        return de.pokerno.protocol.msg.GameplayEvent.class.getSimpleName();
    }

    public String messageFullName() {
        return de.pokerno.protocol.msg.GameplayEvent.class.getName();
    }


    public boolean isInitialized(de.pokerno.protocol.msg.GameplayEvent message) {
        return true;
    }


    public void mergeFrom(Input input, de.pokerno.protocol.msg.GameplayEvent message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, de.pokerno.protocol.msg.GameplayEvent message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_TYPE:
                message.setType(EventType.valueOf(input.readEnum()));
                break;
            case FIELD_GAME:
                message.setGame(input.mergeObject(message.getGame(), proto.wire.GameSchema.getSchema()));
                break;

            case FIELD_STAKE:
                message.setStake(input.mergeObject(message.getStake(), proto.wire.StakeSchema.getSchema()));
                break;

            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_TYPE, FIELD_GAME, FIELD_STAKE };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, de.pokerno.protocol.msg.GameplayEvent message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, de.pokerno.protocol.msg.GameplayEvent message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_TYPE:
                output.writeEnum(FIELD_TYPE, message.getType().number, false);    break;
            case FIELD_GAME:
                if (message.getGame() != null)
                    output.writeObject(FIELD_GAME, message.getGame(), proto.wire.GameSchema.getSchema(), false);

                break;
            case FIELD_STAKE:
                if (message.getStake() != null)
                    output.writeObject(FIELD_STAKE, message.getStake(), proto.wire.StakeSchema.getSchema(), false);

                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_TYPE: return "type";
            case FIELD_GAME: return "game";
            case FIELD_STAKE: return "stake";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("type", FIELD_TYPE);
        fieldMap.put("game", FIELD_GAME);
        fieldMap.put("stake", FIELD_STAKE);
    }
}
