// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from msg.proto

package proto.msg;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class SeatEventSchema
       implements Schema<de.pokerno.protocol.msg.SeatEvent> {

    public enum EventType implements com.dyuproject.protostuff.EnumLite<EventType>
    {
        STATE(1),
        PRESENCE(2),
        PLAYER(3),
        STACK_AMOUNT(4),
        PUT_AMOUNT(5);
        
        public final int number;
        
        private EventType (int number)
        {
            this.number = number;
        }
        
        public int getNumber()
        {
            return number;
        }
        
        public static EventType valueOf(int number)
        {
            switch(number) 
            {
                case 1: return STATE;
                case 2: return PRESENCE;
                case 3: return PLAYER;
                case 4: return STACK_AMOUNT;
                case 5: return PUT_AMOUNT;
                default: return null;
            }
        }
    }


    static final de.pokerno.protocol.msg.SeatEvent DEFAULT_INSTANCE = new de.pokerno.protocol.msg.SeatEvent();
    static final Schema<de.pokerno.protocol.msg.SeatEvent> SCHEMA = new SeatEventSchema();

    public static de.pokerno.protocol.msg.SeatEvent getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<de.pokerno.protocol.msg.SeatEvent> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_TYPE = 1;
    public static final int FIELD_POS = 2;
    public static final int FIELD_SEAT = 3;

    public SeatEventSchema() {}


    public de.pokerno.protocol.msg.SeatEvent newMessage() {
        return new de.pokerno.protocol.msg.SeatEvent();
    }

    public Class<de.pokerno.protocol.msg.SeatEvent> typeClass() {
        return de.pokerno.protocol.msg.SeatEvent.class;
    }

    public String messageName() {
        return de.pokerno.protocol.msg.SeatEvent.class.getSimpleName();
    }

    public String messageFullName() {
        return de.pokerno.protocol.msg.SeatEvent.class.getName();
    }


    public boolean isInitialized(de.pokerno.protocol.msg.SeatEvent message) {
        return true;
    }


    public void mergeFrom(Input input, de.pokerno.protocol.msg.SeatEvent message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, de.pokerno.protocol.msg.SeatEvent message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_TYPE:
                message.setType(EventType.valueOf(input.readEnum()));
                break;
            case FIELD_POS:
                message.setPos(input.readInt32());
                break;
            case FIELD_SEAT:
                message.setSeat(input.mergeObject(message.getSeat(), proto.wire.SeatSchema.getSchema()));
                break;

            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_TYPE, FIELD_POS, FIELD_SEAT };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, de.pokerno.protocol.msg.SeatEvent message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, de.pokerno.protocol.msg.SeatEvent message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_TYPE:
                output.writeEnum(FIELD_TYPE, message.getType().number, false);    break;
            case FIELD_POS:
                output.writeInt32(FIELD_POS, message.getPos(), false);
                break;
            case FIELD_SEAT:
                output.writeObject(FIELD_SEAT, message.getSeat(), proto.wire.SeatSchema.getSchema(), false);

                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_TYPE: return "type";
            case FIELD_POS: return "pos";
            case FIELD_SEAT: return "seat";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("type", FIELD_TYPE);
        fieldMap.put("pos", FIELD_POS);
        fieldMap.put("seat", FIELD_SEAT);
    }
}
