// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from msg.proto

package proto.msg;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class StageEventSchema
       implements Schema<de.pokerno.protocol.msg.StageEvent> {

    public enum EventType implements com.dyuproject.protostuff.EnumLite<EventType>
    {
        START(1),
        STOP(2),
        CANCEL(3);
        
        public final int number;
        
        private EventType (int number)
        {
            this.number = number;
        }
        
        public int getNumber()
        {
            return number;
        }
        
        public static EventType valueOf(int number)
        {
            switch(number) 
            {
                case 1: return START;
                case 2: return STOP;
                case 3: return CANCEL;
                default: return null;
            }
        }
    }
    public enum StageType implements com.dyuproject.protostuff.EnumLite<StageType>
    {
        PLAY(1),
        STREET(2);
        
        public final int number;
        
        private StageType (int number)
        {
            this.number = number;
        }
        
        public int getNumber()
        {
            return number;
        }
        
        public static StageType valueOf(int number)
        {
            switch(number) 
            {
                case 1: return PLAY;
                case 2: return STREET;
                default: return null;
            }
        }
    }


    static final de.pokerno.protocol.msg.StageEvent DEFAULT_INSTANCE = new de.pokerno.protocol.msg.StageEvent();
    static final Schema<de.pokerno.protocol.msg.StageEvent> SCHEMA = new StageEventSchema();

    public static de.pokerno.protocol.msg.StageEvent getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<de.pokerno.protocol.msg.StageEvent> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_TYPE = 1;
    public static final int FIELD_STAGE = 2;
    public static final int FIELD_STREET = 3;

    public StageEventSchema() {}


    public de.pokerno.protocol.msg.StageEvent newMessage() {
        return new de.pokerno.protocol.msg.StageEvent();
    }

    public Class<de.pokerno.protocol.msg.StageEvent> typeClass() {
        return de.pokerno.protocol.msg.StageEvent.class;
    }

    public String messageName() {
        return de.pokerno.protocol.msg.StageEvent.class.getSimpleName();
    }

    public String messageFullName() {
        return de.pokerno.protocol.msg.StageEvent.class.getName();
    }


    public boolean isInitialized(de.pokerno.protocol.msg.StageEvent message) {
        return true;
    }


    public void mergeFrom(Input input, de.pokerno.protocol.msg.StageEvent message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, de.pokerno.protocol.msg.StageEvent message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_TYPE:
                message.setType(EventType.valueOf(input.readEnum()));
                break;
            case FIELD_STAGE:
                message.setStage(StageType.valueOf(input.readEnum()));
                break;
            case FIELD_STREET:
                message.setStreet(proto.wire.StreetType.valueOf(input.readEnum()));
                break;
            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_TYPE, FIELD_STAGE, FIELD_STREET };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, de.pokerno.protocol.msg.StageEvent message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, de.pokerno.protocol.msg.StageEvent message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_TYPE:
                output.writeEnum(FIELD_TYPE, message.getType().number, false);    break;
            case FIELD_STAGE:
                output.writeEnum(FIELD_STAGE, message.getStage().number, false);    break;
            case FIELD_STREET:
                if (message.getStreet() != null)
                    output.writeEnum(FIELD_STREET, message.getStreet().number, false);
                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_TYPE: return "type";
            case FIELD_STAGE: return "stage";
            case FIELD_STREET: return "street";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("type", FIELD_TYPE);
        fieldMap.put("stage", FIELD_STAGE);
        fieldMap.put("street", FIELD_STREET);
    }
}
