// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from msg.proto

package proto.msg;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class TickTimerSchema
       implements Schema<de.pokerno.protocol.msg.TickTimer> {


    static final de.pokerno.protocol.msg.TickTimer DEFAULT_INSTANCE = new de.pokerno.protocol.msg.TickTimer();
    static final Schema<de.pokerno.protocol.msg.TickTimer> SCHEMA = new TickTimerSchema();

    public static de.pokerno.protocol.msg.TickTimer getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<de.pokerno.protocol.msg.TickTimer> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_POS = 1;
    public static final int FIELD_PLAYER = 2;
    public static final int FIELD_TIME_LEFT = 3;
    public static final int FIELD_TIME_BANK = 4;

    public TickTimerSchema() {}


    public de.pokerno.protocol.msg.TickTimer newMessage() {
        return new de.pokerno.protocol.msg.TickTimer();
    }

    public Class<de.pokerno.protocol.msg.TickTimer> typeClass() {
        return de.pokerno.protocol.msg.TickTimer.class;
    }

    public String messageName() {
        return de.pokerno.protocol.msg.TickTimer.class.getSimpleName();
    }

    public String messageFullName() {
        return de.pokerno.protocol.msg.TickTimer.class.getName();
    }


    public boolean isInitialized(de.pokerno.protocol.msg.TickTimer message) {
        return true;
    }


    public void mergeFrom(Input input, de.pokerno.protocol.msg.TickTimer message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, de.pokerno.protocol.msg.TickTimer message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_POS:
                message.setPos(input.readInt32());
                break;
            case FIELD_PLAYER:
                message.setPlayer(input.readString());
                break;
            case FIELD_TIME_LEFT:
                message.setTimeLeft(input.readInt32());
                break;
            case FIELD_TIME_BANK:
                message.setTimeBank(input.readBool());
                break;
            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_POS, FIELD_PLAYER, FIELD_TIME_LEFT, FIELD_TIME_BANK };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, de.pokerno.protocol.msg.TickTimer message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, de.pokerno.protocol.msg.TickTimer message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_POS:
                output.writeInt32(FIELD_POS, message.getPos(), false);
                break;
            case FIELD_PLAYER:
                output.writeString(FIELD_PLAYER, message.getPlayer(), false);
                break;
            case FIELD_TIME_LEFT:
                output.writeInt32(FIELD_TIME_LEFT, message.getTimeLeft(), false);
                break;
            case FIELD_TIME_BANK:
                if (message.isTimeBank() != null)
                    output.writeBool(FIELD_TIME_BANK, message.isTimeBank(), false);
                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_POS: return "pos";
            case FIELD_PLAYER: return "player";
            case FIELD_TIME_LEFT: return "timeLeft";
            case FIELD_TIME_BANK: return "timeBank";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("pos", FIELD_POS);
        fieldMap.put("player", FIELD_PLAYER);
        fieldMap.put("timeLeft", FIELD_TIME_LEFT);
        fieldMap.put("timeBank", FIELD_TIME_BANK);
    }
}
