// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from rpc.proto

package proto.rpc;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class NodeActionSchema
       implements Schema<de.pokerno.protocol.rpc.NodeAction> {

    public enum ActionType implements com.dyuproject.protostuff.EnumLite<ActionType>
    {
        CREATE_ROOM(1);
        
        public final int number;
        
        private ActionType (int number)
        {
            this.number = number;
        }
        
        public int getNumber()
        {
            return number;
        }
        
        public static ActionType valueOf(int number)
        {
            switch(number) 
            {
                case 1: return CREATE_ROOM;
                default: return null;
            }
        }
    }


    static final de.pokerno.protocol.rpc.NodeAction DEFAULT_INSTANCE = new de.pokerno.protocol.rpc.NodeAction();
    static final Schema<de.pokerno.protocol.rpc.NodeAction> SCHEMA = new NodeActionSchema();

    public static de.pokerno.protocol.rpc.NodeAction getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<de.pokerno.protocol.rpc.NodeAction> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_TYPE = 1;
    public static final int FIELD_CREATE_ROOM = 2;

    public NodeActionSchema() {}


    public de.pokerno.protocol.rpc.NodeAction newMessage() {
        return new de.pokerno.protocol.rpc.NodeAction();
    }

    public Class<de.pokerno.protocol.rpc.NodeAction> typeClass() {
        return de.pokerno.protocol.rpc.NodeAction.class;
    }

    public String messageName() {
        return de.pokerno.protocol.rpc.NodeAction.class.getSimpleName();
    }

    public String messageFullName() {
        return de.pokerno.protocol.rpc.NodeAction.class.getName();
    }


    public boolean isInitialized(de.pokerno.protocol.rpc.NodeAction message) {
        return true;
    }


    public void mergeFrom(Input input, de.pokerno.protocol.rpc.NodeAction message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, de.pokerno.protocol.rpc.NodeAction message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_TYPE:
                message.setType(ActionType.valueOf(input.readEnum()));
                break;
            case FIELD_CREATE_ROOM:
                message.setCreateRoom(input.mergeObject(message.getCreateRoom(), CreateRoomSchema.getSchema()));
                break;

            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_TYPE, FIELD_CREATE_ROOM };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, de.pokerno.protocol.rpc.NodeAction message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, de.pokerno.protocol.rpc.NodeAction message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_TYPE:
                output.writeEnum(FIELD_TYPE, message.getType().number, false);    break;
            case FIELD_CREATE_ROOM:
                if (message.getCreateRoom() != null)
                    output.writeObject(FIELD_CREATE_ROOM, message.getCreateRoom(), CreateRoomSchema.getSchema(), false);

                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_TYPE: return "type";
            case FIELD_CREATE_ROOM: return "createRoom";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("type", FIELD_TYPE);
        fieldMap.put("createRoom", FIELD_CREATE_ROOM);
    }
}
