// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from cmd.proto

package de.pokerno.protocol.cmd;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class ChatSchema
       implements Schema<Chat> {


    static final Chat DEFAULT_INSTANCE = new Chat();
    static final Schema<Chat> SCHEMA = new ChatSchema();

    public static Chat getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<Chat> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_PLAYER = 1;
    public static final int FIELD_BODY = 2;

    public ChatSchema() {}


    public Chat newMessage() {
        return new Chat();
    }

    public Class<Chat> typeClass() {
        return Chat.class;
    }

    public String messageName() {
        return Chat.class.getSimpleName();
    }

    public String messageFullName() {
        return Chat.class.getName();
    }


    public boolean isInitialized(Chat message) {
        return true;
    }


    public void mergeFrom(Input input, Chat message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, Chat message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_PLAYER:
                message.setPlayer(input.readString());
                break;
            case FIELD_BODY:
                message.setBody(input.readString());
                break;
            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_PLAYER, FIELD_BODY };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, Chat message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, Chat message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_PLAYER:
                output.writeString(FIELD_PLAYER, message.getPlayer(), false);
                break;
            case FIELD_BODY:
                output.writeString(FIELD_BODY, message.getBody(), false);
                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_PLAYER: return "player";
            case FIELD_BODY: return "body";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("player", FIELD_PLAYER);
        fieldMap.put("body", FIELD_BODY);
    }
}
