// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from cmd.proto

package de.pokerno.protocol.cmd;

import java.io.IOException;

import com.dyuproject.protostuff.ByteString;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class DiscardCardsSchema
       implements Schema<DiscardCards> {


    static final DiscardCards DEFAULT_INSTANCE = new DiscardCards();
    static final Schema<DiscardCards> SCHEMA = new DiscardCardsSchema();

    public static DiscardCards getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<DiscardCards> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_PLAYER = 1;
    public static final int FIELD_CARDS = 2;

    public DiscardCardsSchema() {}


    public DiscardCards newMessage() {
        return new DiscardCards();
    }

    public Class<DiscardCards> typeClass() {
        return DiscardCards.class;
    }

    public String messageName() {
        return DiscardCards.class.getSimpleName();
    }

    public String messageFullName() {
        return DiscardCards.class.getName();
    }


    public boolean isInitialized(DiscardCards message) {
        return true;
    }


    public void mergeFrom(Input input, DiscardCards message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, DiscardCards message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_PLAYER:
                message.setPlayer(input.readString());
                break;
            case FIELD_CARDS:
                message.setCards(input.readBytes());
                break;
            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_PLAYER, FIELD_CARDS };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, DiscardCards message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, DiscardCards message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_PLAYER:
                output.writeString(FIELD_PLAYER, message.getPlayer(), false);
                break;
            case FIELD_CARDS:
                output.writeBytes(FIELD_CARDS, message.getCards(), false);
                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_PLAYER: return "player";
            case FIELD_CARDS: return "cards";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("player", FIELD_PLAYER);
        fieldMap.put("cards", FIELD_CARDS);
    }
}
