// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from msg.proto

package de.pokerno.protocol.msg;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class CardsDiscardSchema
       implements Schema<CardsDiscard> {


    static final CardsDiscard DEFAULT_INSTANCE = new CardsDiscard();
    static final Schema<CardsDiscard> SCHEMA = new CardsDiscardSchema();

    public static CardsDiscard getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<CardsDiscard> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_POS = 1;
    public static final int FIELD_PLAYER = 2;
    public static final int FIELD_CARDS_NUM = 3;

    public CardsDiscardSchema() {}


    public CardsDiscard newMessage() {
        return new CardsDiscard();
    }

    public Class<CardsDiscard> typeClass() {
        return CardsDiscard.class;
    }

    public String messageName() {
        return CardsDiscard.class.getSimpleName();
    }

    public String messageFullName() {
        return CardsDiscard.class.getName();
    }


    public boolean isInitialized(CardsDiscard message) {
        return true;
    }


    public void mergeFrom(Input input, CardsDiscard message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, CardsDiscard message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_POS:
                message.setPos(input.readInt32());
                break;
            case FIELD_PLAYER:
                message.setPlayer(input.readString());
                break;
            case FIELD_CARDS_NUM:
                message.setCardsNum(input.readInt32());
                break;
            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_POS, FIELD_PLAYER, FIELD_CARDS_NUM };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, CardsDiscard message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, CardsDiscard message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_POS:
                output.writeInt32(FIELD_POS, message.getPos(), false);
                break;
            case FIELD_PLAYER:
                output.writeString(FIELD_PLAYER, message.getPlayer(), false);
                break;
            case FIELD_CARDS_NUM:
                output.writeInt32(FIELD_CARDS_NUM, message.getCardsNum(), false);
                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_POS: return "pos";
            case FIELD_PLAYER: return "player";
            case FIELD_CARDS_NUM: return "cardsNum";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("pos", FIELD_POS);
        fieldMap.put("player", FIELD_PLAYER);
        fieldMap.put("cardsNum", FIELD_CARDS_NUM);
    }
}
