// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from msg.proto

package de.pokerno.protocol.msg;

import java.io.IOException;

import com.dyuproject.protostuff.ByteString;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class DealCardsSchema
       implements Schema<DealCards> {


    static final DealCards DEFAULT_INSTANCE = new DealCards();
    static final Schema<DealCards> SCHEMA = new DealCardsSchema();

    public static DealCards getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<DealCards> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_TYPE = 1;
    public static final int FIELD_CARDS = 2;
    public static final int FIELD_POS = 3;
    public static final int FIELD_PLAYER = 4;
    public static final int FIELD_CARDS_NUM = 5;

    public DealCardsSchema() {}


    public DealCards newMessage() {
        return new DealCards();
    }

    public Class<DealCards> typeClass() {
        return DealCards.class;
    }

    public String messageName() {
        return DealCards.class.getSimpleName();
    }

    public String messageFullName() {
        return DealCards.class.getName();
    }


    public boolean isInitialized(DealCards message) {
        return true;
    }


    public void mergeFrom(Input input, DealCards message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, DealCards message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_TYPE:
                message.setType(de.pokerno.protocol.wire.DealType.valueOf(input.readEnum()));
                break;
            case FIELD_CARDS:
                message.setCards(input.readBytes());
                break;
            case FIELD_POS:
                message.setPos(input.readInt32());
                break;
            case FIELD_PLAYER:
                message.setPlayer(input.readString());
                break;
            case FIELD_CARDS_NUM:
                message.setCardsNum(input.readInt32());
                break;
            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_TYPE, FIELD_CARDS, FIELD_POS, FIELD_PLAYER, FIELD_CARDS_NUM };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, DealCards message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, DealCards message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_TYPE:
                output.writeEnum(FIELD_TYPE, message.getType().number, false);    break;
            case FIELD_CARDS:
                if (message.getCards() != null)
                    output.writeBytes(FIELD_CARDS, message.getCards(), false);
                break;
            case FIELD_POS:
                if (message.getPos() != null)
                    output.writeInt32(FIELD_POS, message.getPos(), false);
                break;
            case FIELD_PLAYER:
                if (message.getPlayer() != null)
                    output.writeString(FIELD_PLAYER, message.getPlayer(), false);
                break;
            case FIELD_CARDS_NUM:
                if (message.getCardsNum() != null)
                    output.writeInt32(FIELD_CARDS_NUM, message.getCardsNum(), false);
                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_TYPE: return "type";
            case FIELD_CARDS: return "cards";
            case FIELD_POS: return "pos";
            case FIELD_PLAYER: return "player";
            case FIELD_CARDS_NUM: return "cardsNum";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("type", FIELD_TYPE);
        fieldMap.put("cards", FIELD_CARDS);
        fieldMap.put("pos", FIELD_POS);
        fieldMap.put("player", FIELD_PLAYER);
        fieldMap.put("cardsNum", FIELD_CARDS_NUM);
    }
}
