// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from msg.proto

package de.pokerno.protocol.msg;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class JoinTableSchema
       implements Schema<JoinTable> {


    static final JoinTable DEFAULT_INSTANCE = new JoinTable();
    static final Schema<JoinTable> SCHEMA = new JoinTableSchema();

    public static JoinTable getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<JoinTable> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_POS = 1;
    public static final int FIELD_AMOUNT = 3;

    public JoinTableSchema() {}


    public JoinTable newMessage() {
        return new JoinTable();
    }

    public Class<JoinTable> typeClass() {
        return JoinTable.class;
    }

    public String messageName() {
        return JoinTable.class.getSimpleName();
    }

    public String messageFullName() {
        return JoinTable.class.getName();
    }


    public boolean isInitialized(JoinTable message) {
        return true;
    }


    public void mergeFrom(Input input, JoinTable message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, JoinTable message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_POS:
                message.setPos(input.readInt32());
                break;
            case FIELD_AMOUNT:
                message.setAmount(input.readDouble());
                break;
            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_POS, FIELD_AMOUNT };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, JoinTable message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, JoinTable message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_POS:
                output.writeInt32(FIELD_POS, message.getPos(), false);
                break;
            case FIELD_AMOUNT:
                output.writeDouble(FIELD_AMOUNT, message.getAmount(), false);
                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_POS: return "pos";
            case FIELD_AMOUNT: return "amount";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("pos", FIELD_POS);
        fieldMap.put("amount", FIELD_AMOUNT);
    }
}
