// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from msg.proto

package de.pokerno.protocol.msg;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class RequireBetSchema
       implements Schema<RequireBet> {


    static final RequireBet DEFAULT_INSTANCE = new RequireBet();
    static final Schema<RequireBet> SCHEMA = new RequireBetSchema();

    public static RequireBet getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<RequireBet> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_POS = 1;
    public static final int FIELD_PLAYER = 2;
    public static final int FIELD_CALL = 3;
    public static final int FIELD_RAISE = 4;

    public RequireBetSchema() {}


    public RequireBet newMessage() {
        return new RequireBet();
    }

    public Class<RequireBet> typeClass() {
        return RequireBet.class;
    }

    public String messageName() {
        return RequireBet.class.getSimpleName();
    }

    public String messageFullName() {
        return RequireBet.class.getName();
    }


    public boolean isInitialized(RequireBet message) {
        return true;
    }


    public void mergeFrom(Input input, RequireBet message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, RequireBet message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_POS:
                message.setPos(input.readInt32());
                break;
            case FIELD_PLAYER:
                message.setPlayer(input.readString());
                break;
            case FIELD_CALL:
                message.setCall(input.readDouble());
                break;
            case FIELD_RAISE:
                message.setRaise(input.mergeObject(message.getRaise(), de.pokerno.protocol.wire.RangeSchema.getSchema()));
                break;

            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_POS, FIELD_PLAYER, FIELD_CALL, FIELD_RAISE };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, RequireBet message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, RequireBet message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_POS:
                output.writeInt32(FIELD_POS, message.getPos(), false);
                break;
            case FIELD_PLAYER:
                output.writeString(FIELD_PLAYER, message.getPlayer(), false);
                break;
            case FIELD_CALL:
                output.writeDouble(FIELD_CALL, message.getCall(), false);
                break;
            case FIELD_RAISE:
                output.writeObject(FIELD_RAISE, message.getRaise(), de.pokerno.protocol.wire.RangeSchema.getSchema(), false);

                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_POS: return "pos";
            case FIELD_PLAYER: return "player";
            case FIELD_CALL: return "call";
            case FIELD_RAISE: return "raise";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("pos", FIELD_POS);
        fieldMap.put("player", FIELD_PLAYER);
        fieldMap.put("call", FIELD_CALL);
        fieldMap.put("raise", FIELD_RAISE);
    }
}
