// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from msg.proto

package de.pokerno.protocol.msg;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class RequireDiscardSchema
       implements Schema<RequireDiscard> {


    static final RequireDiscard DEFAULT_INSTANCE = new RequireDiscard();
    static final Schema<RequireDiscard> SCHEMA = new RequireDiscardSchema();

    public static RequireDiscard getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<RequireDiscard> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_POS = 1;
    public static final int FIELD_PLAYER = 2;

    public RequireDiscardSchema() {}


    public RequireDiscard newMessage() {
        return new RequireDiscard();
    }

    public Class<RequireDiscard> typeClass() {
        return RequireDiscard.class;
    }

    public String messageName() {
        return RequireDiscard.class.getSimpleName();
    }

    public String messageFullName() {
        return RequireDiscard.class.getName();
    }


    public boolean isInitialized(RequireDiscard message) {
        return true;
    }


    public void mergeFrom(Input input, RequireDiscard message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, RequireDiscard message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_POS:
                message.setPos(input.readInt32());
                break;
            case FIELD_PLAYER:
                message.setPlayer(input.readString());
                break;
            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_POS, FIELD_PLAYER };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, RequireDiscard message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, RequireDiscard message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_POS:
                output.writeInt32(FIELD_POS, message.getPos(), false);
                break;
            case FIELD_PLAYER:
                output.writeString(FIELD_PLAYER, message.getPlayer(), false);
                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_POS: return "pos";
            case FIELD_PLAYER: return "player";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("pos", FIELD_POS);
        fieldMap.put("player", FIELD_PLAYER);
    }
}
