// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from msg.proto

package de.pokerno.protocol.msg;

import java.io.IOException;

import com.dyuproject.protostuff.ByteString;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class ShowCardsSchema
       implements Schema<ShowCards> {

    public enum ShowType implements com.dyuproject.protostuff.EnumLite<ShowType>
    {
        SHOW(1),
        MUCK(2);
        
        public final int number;
        
        private ShowType (int number)
        {
            this.number = number;
        }
        
        public int getNumber()
        {
            return number;
        }
        
        public static ShowType valueOf(int number)
        {
            switch(number) 
            {
                case 1: return SHOW;
                case 2: return MUCK;
                default: return null;
            }
        }
    }


    static final ShowCards DEFAULT_INSTANCE = new ShowCards();
    static final Schema<ShowCards> SCHEMA = new ShowCardsSchema();

    public static ShowCards getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<ShowCards> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_TYPE = 1;
    public static final int FIELD_CARDS = 4;

    public ShowCardsSchema() {}


    public ShowCards newMessage() {
        return new ShowCards();
    }

    public Class<ShowCards> typeClass() {
        return ShowCards.class;
    }

    public String messageName() {
        return ShowCards.class.getSimpleName();
    }

    public String messageFullName() {
        return ShowCards.class.getName();
    }


    public boolean isInitialized(ShowCards message) {
        return true;
    }


    public void mergeFrom(Input input, ShowCards message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, ShowCards message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_TYPE:
                message.setType(ShowType.valueOf(input.readEnum()));
                break;
            case FIELD_CARDS:
                message.setCards(input.readBytes());
                break;
            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_TYPE, FIELD_CARDS };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, ShowCards message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, ShowCards message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_TYPE:
                output.writeEnum(FIELD_TYPE, message.getType().number, false);    break;
            case FIELD_CARDS:
                if (message.getCards() != null)
                    output.writeBytes(FIELD_CARDS, message.getCards(), false);
                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_TYPE: return "type";
            case FIELD_CARDS: return "cards";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("type", FIELD_TYPE);
        fieldMap.put("cards", FIELD_CARDS);
    }
}
