// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from msg.proto

package de.pokerno.protocol.msg;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class StartSchema
       implements Schema<Start> {


    static final Start DEFAULT_INSTANCE = new Start();
    static final Schema<Start> SCHEMA = new StartSchema();

    public static Start getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<Start> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_TABLE = 1;
    public static final int FIELD_VARIATION = 2;
    public static final int FIELD_STAKE = 3;
    public static final int FIELD_DEAL = 4;

    public StartSchema() {}


    public Start newMessage() {
        return new Start();
    }

    public Class<Start> typeClass() {
        return Start.class;
    }

    public String messageName() {
        return Start.class.getSimpleName();
    }

    public String messageFullName() {
        return Start.class.getName();
    }


    public boolean isInitialized(Start message) {
        return true;
    }


    public void mergeFrom(Input input, Start message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, Start message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_TABLE:
                message.setTable(input.mergeObject(message.getTable(), de.pokerno.protocol.wire.TableSchema.getSchema()));
                break;

            case FIELD_VARIATION:
                message.setVariation(input.mergeObject(message.getVariation(), de.pokerno.protocol.wire.VariationSchema.getSchema()));
                break;

            case FIELD_STAKE:
                message.setStake(input.mergeObject(message.getStake(), de.pokerno.protocol.wire.StakeSchema.getSchema()));
                break;

            case FIELD_DEAL:
                message.setDeal(input.mergeObject(message.getDeal(), DealSchema.getSchema()));
                break;

            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_TABLE, FIELD_VARIATION, FIELD_STAKE, FIELD_DEAL };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, Start message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, Start message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_TABLE:
                output.writeObject(FIELD_TABLE, message.getTable(), de.pokerno.protocol.wire.TableSchema.getSchema(), false);

                break;
            case FIELD_VARIATION:
                output.writeObject(FIELD_VARIATION, message.getVariation(), de.pokerno.protocol.wire.VariationSchema.getSchema(), false);

                break;
            case FIELD_STAKE:
                output.writeObject(FIELD_STAKE, message.getStake(), de.pokerno.protocol.wire.StakeSchema.getSchema(), false);

                break;
            case FIELD_DEAL:
                output.writeObject(FIELD_DEAL, message.getDeal(), DealSchema.getSchema(), false);

                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_TABLE: return "table";
            case FIELD_VARIATION: return "variation";
            case FIELD_STAKE: return "stake";
            case FIELD_DEAL: return "deal";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("table", FIELD_TABLE);
        fieldMap.put("variation", FIELD_VARIATION);
        fieldMap.put("stake", FIELD_STAKE);
        fieldMap.put("deal", FIELD_DEAL);
    }
}
