// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from msg.proto

package de.pokerno.protocol.msg;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class TableEventSchema
       implements Schema<TableEvent> {

    public enum EventType implements com.dyuproject.protostuff.EnumLite<EventType>
    {
        BUTTON(1),
        STATE(2);
        
        public final int number;
        
        private EventType (int number)
        {
            this.number = number;
        }
        
        public int getNumber()
        {
            return number;
        }
        
        public static EventType valueOf(int number)
        {
            switch(number) 
            {
                case 1: return BUTTON;
                case 2: return STATE;
                default: return null;
            }
        }
    }
    public enum TableState implements com.dyuproject.protostuff.EnumLite<TableState>
    {
        ACTIVE(1);
        
        public final int number;
        
        private TableState (int number)
        {
            this.number = number;
        }
        
        public int getNumber()
        {
            return number;
        }
        
        public static TableState valueOf(int number)
        {
            switch(number) 
            {
                case 1: return ACTIVE;
                default: return null;
            }
        }
    }


    static final TableEvent DEFAULT_INSTANCE = new TableEvent();
    static final Schema<TableEvent> SCHEMA = new TableEventSchema();

    public static TableEvent getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<TableEvent> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_TYPE = 1;
    public static final int FIELD_BUTTON = 2;
    public static final int FIELD_STATE = 3;

    public TableEventSchema() {}


    public TableEvent newMessage() {
        return new TableEvent();
    }

    public Class<TableEvent> typeClass() {
        return TableEvent.class;
    }

    public String messageName() {
        return TableEvent.class.getSimpleName();
    }

    public String messageFullName() {
        return TableEvent.class.getName();
    }


    public boolean isInitialized(TableEvent message) {
        return true;
    }


    public void mergeFrom(Input input, TableEvent message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, TableEvent message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_TYPE:
                message.setType(EventType.valueOf(input.readEnum()));
                break;
            case FIELD_BUTTON:
                message.setButton(input.readInt32());
                break;
            case FIELD_STATE:
                message.setState(TableState.valueOf(input.readEnum()));
                break;
            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_TYPE, FIELD_BUTTON, FIELD_STATE };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, TableEvent message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, TableEvent message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_TYPE:
                output.writeEnum(FIELD_TYPE, message.getType().number, false);    break;
            case FIELD_BUTTON:
                if (message.getButton() != null)
                    output.writeInt32(FIELD_BUTTON, message.getButton(), false);
                break;
            case FIELD_STATE:
                if (message.getState() != null)
                    output.writeEnum(FIELD_STATE, message.getState().number, false);
                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_TYPE: return "type";
            case FIELD_BUTTON: return "button";
            case FIELD_STATE: return "state";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("type", FIELD_TYPE);
        fieldMap.put("button", FIELD_BUTTON);
        fieldMap.put("state", FIELD_STATE);
    }
}
