// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from rpc.proto

package de.pokerno.protocol.rpc;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class RoomActionSchema
       implements Schema<RoomAction> {

    public enum ActionType implements com.dyuproject.protostuff.EnumLite<ActionType>
    {
        CLOSE(1),
        PAUSE(2),
        PAUSE_BREAK(4),
        PAUSE_ADDON_BREAK(5),
        PAUSE_BUBBLE(6),
        PAUSE_PRIZE_SPLIT(7),
        RESUME(8),
        CANCEL_CURRENT_DEAL(9),
        MAINTENANCE(10);
        
        public final int number;
        
        private ActionType (int number)
        {
            this.number = number;
        }
        
        public int getNumber()
        {
            return number;
        }
        
        public static ActionType valueOf(int number)
        {
            switch(number) 
            {
                case 1: return CLOSE;
                case 2: return PAUSE;
                case 4: return PAUSE_BREAK;
                case 5: return PAUSE_ADDON_BREAK;
                case 6: return PAUSE_BUBBLE;
                case 7: return PAUSE_PRIZE_SPLIT;
                case 8: return RESUME;
                case 9: return CANCEL_CURRENT_DEAL;
                case 10: return MAINTENANCE;
                default: return null;
            }
        }
    }


    static final RoomAction DEFAULT_INSTANCE = new RoomAction();
    static final Schema<RoomAction> SCHEMA = new RoomActionSchema();

    public static RoomAction getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<RoomAction> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_TYPE = 1;
    public static final int FIELD_ID = 2;
    public static final int FIELD_DEADLINE = 3;

    public RoomActionSchema() {}


    public RoomAction newMessage() {
        return new RoomAction();
    }

    public Class<RoomAction> typeClass() {
        return RoomAction.class;
    }

    public String messageName() {
        return RoomAction.class.getSimpleName();
    }

    public String messageFullName() {
        return RoomAction.class.getName();
    }


    public boolean isInitialized(RoomAction message) {
        return true;
    }


    public void mergeFrom(Input input, RoomAction message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, RoomAction message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_TYPE:
                message.setType(ActionType.valueOf(input.readEnum()));
                break;
            case FIELD_ID:
                message.setId(input.readString());
                break;
            case FIELD_DEADLINE:
                message.setDeadline(input.readInt32());
                break;
            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_TYPE, FIELD_ID, FIELD_DEADLINE };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, RoomAction message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, RoomAction message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_TYPE:
                output.writeEnum(FIELD_TYPE, message.getType().number, false);    break;
            case FIELD_ID:
                output.writeString(FIELD_ID, message.getId(), false);
                break;
            case FIELD_DEADLINE:
                if (message.getDeadline() != null)
                    output.writeInt32(FIELD_DEADLINE, message.getDeadline(), false);
                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_TYPE: return "type";
            case FIELD_ID: return "id";
            case FIELD_DEADLINE: return "deadline";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("type", FIELD_TYPE);
        fieldMap.put("id", FIELD_ID);
        fieldMap.put("deadline", FIELD_DEADLINE);
    }
}
