// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from wire.proto

package proto.wire;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class MinMaxSchema
       implements Schema<de.pokerno.protocol.wire.MinMax> {


    static final de.pokerno.protocol.wire.MinMax DEFAULT_INSTANCE = new de.pokerno.protocol.wire.MinMax();
    static final Schema<de.pokerno.protocol.wire.MinMax> SCHEMA = new MinMaxSchema();

    public static de.pokerno.protocol.wire.MinMax getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<de.pokerno.protocol.wire.MinMax> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_MIN = 1;
    public static final int FIELD_MAX = 2;

    public MinMaxSchema() {}


    public de.pokerno.protocol.wire.MinMax newMessage() {
        return new de.pokerno.protocol.wire.MinMax();
    }

    public Class<de.pokerno.protocol.wire.MinMax> typeClass() {
        return de.pokerno.protocol.wire.MinMax.class;
    }

    public String messageName() {
        return de.pokerno.protocol.wire.MinMax.class.getSimpleName();
    }

    public String messageFullName() {
        return de.pokerno.protocol.wire.MinMax.class.getName();
    }


    public boolean isInitialized(de.pokerno.protocol.wire.MinMax message) {
        return true;
    }


    public void mergeFrom(Input input, de.pokerno.protocol.wire.MinMax message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, de.pokerno.protocol.wire.MinMax message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_MIN:
                message.setMin(input.readDouble());
                break;
            case FIELD_MAX:
                message.setMax(input.readDouble());
                break;
            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_MIN, FIELD_MAX };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, de.pokerno.protocol.wire.MinMax message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, de.pokerno.protocol.wire.MinMax message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_MIN:
                output.writeDouble(FIELD_MIN, message.getMin(), false);
                break;
            case FIELD_MAX:
                output.writeDouble(FIELD_MAX, message.getMax(), false);
                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_MIN: return "min";
            case FIELD_MAX: return "max";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("min", FIELD_MIN);
        fieldMap.put("max", FIELD_MAX);
    }
}
