// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from wire.proto

package proto.wire;

import java.io.IOException;

import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public class VariationSchema
       implements Schema<de.pokerno.protocol.wire.Variation> {

    public enum VariationType implements com.dyuproject.protostuff.EnumLite<VariationType>
    {
        GAME(1),
        MIX(2);
        
        public final int number;
        
        private VariationType (int number)
        {
            this.number = number;
        }
        
        public int getNumber()
        {
            return number;
        }
        
        public static VariationType valueOf(int number)
        {
            switch(number) 
            {
                case 1: return GAME;
                case 2: return MIX;
                default: return null;
            }
        }
    }


    static final de.pokerno.protocol.wire.Variation DEFAULT_INSTANCE = new de.pokerno.protocol.wire.Variation();
    static final Schema<de.pokerno.protocol.wire.Variation> SCHEMA = new VariationSchema();

    public static de.pokerno.protocol.wire.Variation getDefaultInstance() { return DEFAULT_INSTANCE; }
    public static Schema<de.pokerno.protocol.wire.Variation> getSchema() { return SCHEMA; }

    public static final int FIELD_NONE = 0;
    public static final int FIELD_TYPE = 1;
    public static final int FIELD_GAME = 2;
    public static final int FIELD_MIX = 3;

    public VariationSchema() {}


    public de.pokerno.protocol.wire.Variation newMessage() {
        return new de.pokerno.protocol.wire.Variation();
    }

    public Class<de.pokerno.protocol.wire.Variation> typeClass() {
        return de.pokerno.protocol.wire.Variation.class;
    }

    public String messageName() {
        return de.pokerno.protocol.wire.Variation.class.getSimpleName();
    }

    public String messageFullName() {
        return de.pokerno.protocol.wire.Variation.class.getName();
    }


    public boolean isInitialized(de.pokerno.protocol.wire.Variation message) {
        return true;
    }


    public void mergeFrom(Input input, de.pokerno.protocol.wire.Variation message) throws IOException {
        for (int fieldIx = input.readFieldNumber(this); fieldIx != FIELD_NONE; fieldIx = input.readFieldNumber(this)) {
            mergeFrom(input, message, fieldIx);
        }
    }

    public void mergeFrom(Input input, de.pokerno.protocol.wire.Variation message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                return;
            case FIELD_TYPE:
                message.setType(VariationType.valueOf(input.readEnum()));
                break;
            case FIELD_GAME:
                message.setGame(input.mergeObject(message.getGame(), GameSchema.getSchema()));
                break;

            case FIELD_MIX:
                message.setMix(input.mergeObject(message.getMix(), MixSchema.getSchema()));
                break;

            default:
                input.handleUnknownField(fieldIx, this);
        }
    }


    private static int[] FIELDS_TO_WRITE = { FIELD_TYPE, FIELD_GAME, FIELD_MIX };

    public int[] getWriteFields() { return FIELDS_TO_WRITE; }

    public void writeTo(Output output, de.pokerno.protocol.wire.Variation message) throws IOException {
        int[] toWrite = getWriteFields();
        for (int i = 0; i < toWrite.length; i++) {
            writeTo(output, message, toWrite[i]);
        }
    }

    public void writeTo(Output output, de.pokerno.protocol.wire.Variation message, int fieldIx) throws IOException {
        switch (fieldIx) {
            case FIELD_NONE:
                break;
            case FIELD_TYPE:
                output.writeEnum(FIELD_TYPE, message.getType().number, false);    break;
            case FIELD_GAME:
                if (message.getGame() != null)
                    output.writeObject(FIELD_GAME, message.getGame(), GameSchema.getSchema(), false);

                break;
            case FIELD_MIX:
                if (message.getMix() != null)
                    output.writeObject(FIELD_MIX, message.getMix(), MixSchema.getSchema(), false);

                break;
            default:
                break;
        }
    }

    public String getFieldName(int number) {
        switch(number) {
            case FIELD_TYPE: return "type";
            case FIELD_GAME: return "game";
            case FIELD_MIX: return "mix";
            default: return null;
        }
    }

    public int getFieldNumber(String name) {
        final Integer number = fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    final java.util.Map<String, Integer> fieldMap = new java.util.HashMap<String, Integer>(); {
        fieldMap.put("type", FIELD_TYPE);
        fieldMap.put("game", FIELD_GAME);
        fieldMap.put("mix", FIELD_MIX);
    }
}
